image: golang:latest@sha256:3680233e3204827fbdc66088528ae6d4b3d034f51d03a99d454f6de034888244

stages:
  - test
  - release

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

release:
  stage: release
  image:
    name: goreleaser/goreleaser@sha256:7077423cf5ef643ff56a34b58f93c1364e927e5c3dfa470eeabc44cab1a9c72b
    entrypoint: ['']
  only:
    refs:
      - tags
  variables:
    GIT_DEPTH: "0"
    GITLAB_TOKEN: "${GORELEASER_TOKEN}"
  script:
    - mkdir -p webex-notifier
    - go build -o webex-notifier  ./...
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - goreleaser release --rm-dist
