image: golang:latest@sha256:ae5a2316d12f3e78fd99177dad452e6ad4f240af2d71d57b480c3477f250fec6

stages:
  - test
  - release

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

release:
  stage: release
  image:
    name: goreleaser/goreleaser@sha256:054eefd282c02233a2556ce2d1a60cd2f51dc565ffc2520dc38b5deb4dd1ad30
    entrypoint: ['']
  only:
    refs:
      - tags
  variables:
    GIT_DEPTH: "0"
    GITLAB_TOKEN: "${GORELEASER_TOKEN}"
  script:
    - mkdir -p webex-notifier
    - go build -o webex-notifier  ./...
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - goreleaser release --rm-dist
