image: golang:latest@sha256:6df14f4a4bc9d979a3721f488981e0d1b318006377e473ed23d026796f5f4c0a

stages:
  - test
  - release

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

release:
  stage: release
  image:
    name: goreleaser/goreleaser@sha256:579eee23514fa647adcc669b5875f866f1c1faf5a0464aec4614a9121684c06c
    entrypoint: ['']
  only:
    refs:
      - tags
  variables:
    GIT_DEPTH: "0"
    GITLAB_TOKEN: "${GORELEASER_TOKEN}"
  script:
    - mkdir -p webex-notifier
    - go build -o webex-notifier  ./...
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - goreleaser release --rm-dist
