project_name: webex-notifier

builds:
  - env: [CGO_ENABLED=0]
    ldflags:
      - -s -w -X webex-notifier/conf.version={{.Tag }}
dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: goreleaser.dockerfile
    image_templates:
      - 'ghcr.io/telekom-mms/webex-notifier:{{ .Tag }}'
      - 'ghcr.io/telekom-mms/webex-notifier:latest'
